### ISSUE TITLE
Connecting Front and Back End Apps

### ISSUE THREAD

**Issue by scooter7** [Longwater1234/WedemyClient#175]
Hi,

Are the front and back end repos automatically integrated assuming that they're hosted on the same server?

Thanks!

**Comment by Longwater1234** [comment]
Hello, yes. By default they are. In dev mode, they communicate through (localhost). 

But in production, you **should** explicitly set PORT and FRONTEND_URL in backend env. (See application-prod.yml)

And for frontend, you should set BACKEND_URL. (See env.sample)

**Comment by Longwater1234** [comment]
@scooter7 No problem. 😃If you face any problems, feel free to post an Issue here or in the Backend Repo

**Comment by scooter7** [comment]
Will do! Thanks again!
