### ISSUE TITLE
Husky Installation failed on Windows

### ISSUE THREAD

**Issue by scooter7** [Longwater1234/WedemyClient#176]
Hi,

After downloading the files and attempting "npm install," I got the following message in my Windows command prompt:

> wedemyvite@2.0.0 prepare
> husky install

husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
npm ERR! code 1
npm ERR! path C:\Users\jvineburgh\OneDrive - Clarus Corporation\Desktop\WedemyClient-main
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c husky install

**Comment by Longwater1234** [comment]
@scooter7 oh, since you didn't use Git to download, you may remove husky from `package.json`, then try to install again.

TLDR; Husky depends on .git directory, it tracks commit changes, then apply lint / formatting.

**Comment by Longwater1234** [comment]
Another quick solution is to remove husky directly. Learn [more](https://typicode.github.io/husky/getting-started.html#uninstall) 

```bash
npm uninstall husky
```

**Comment by Longwater1234** [comment]
@scooter7 hello, any updates?

**Comment by scooter7** [comment]
Hi @Longwater1234 ,

I believe that I got the front end installed.

Now, I need to try the backend installation.

I assume that all of the course additions, styling, etc. are done from the backend?

Thanks!

**Comment by Longwater1234** [comment]
@scooter7 hello again! Good to hear you succeeded. The backend is only for Student platform. Does not contain admin platform. So you will have to add data in database manually, sorry. Or you can extend by creating a page for Admin and backend service for it.

**Comment by Longwater1234** [comment]
I have a sample .sql in the backend repo with some sample data to play with. See the link in README. You can import it to your database to test. Otherwise for now you need to import data manually in database. You can use any MySQL GUI client.

**Comment by Longwater1234** [comment]
@scooter7 Hi, did you succeed to add some data?
